# Site settings
title: "BioVis 2024"
email: "website@biovis.net"
description: "Biological Data Visualization"
baseurl: "/2024"
url: "http://biovis.net"
conferenceshort: "BioVis 2024"

#FIX ME: the event number is most likely not correct
#eventNum: "12th"

IEEE_conference_date: "October 13 - 18, 2024"
IEEE_conference_place: "Florida, USA"

year: 2024

# Old deadlines so I remember what they're called
# When everything breaks
IEEE_deadline_submission: "TBA"
IEEE_deadline_notification: "TBA"
IEEE_deadline_camera: "TBA"
#IEEE_deadline_poster: "TBD"

ismb_conference_name: "ISMB 2024"
ismb_conference_link: "https://www.iscb.org/ismb2024"
ismb_conference_registration_link: "https://www.iscb.org/ismb2024-register"
ismb_conference_date: "July 12 - 16, 2024"
ismb_conference_place: "Montreal, Quebec, Canada - Palais des congrès de Montréal"
ismb_conference_key_dates_link: "https://www.iscb.org/ismb2024/key-dates"

ismb_cosi_date: "July 14, 2024"

ismb_paper_submission_deadline: "January 25, 2024"
ismb_paper_conditional_acceptance: "March 7, 2024"
ismb_paper_revision_deadline: "March 18, 2024"
ismb_paper_final_acceptance: "April 2, 2024"

ismb_talk_submission_deadline: "April 19, 2024"
ismb_talk_acceptance: "May 13, 2024"

ismb_poster_submission_deadline: "April 19, 2024"
ismb_poster_acceptance: "May 13, 2024"
ismb_poster_late_submission_deadline: "May 20, 2024"
ismb_poster_late_acceptance: "May 28, 2024"

ismb_paper_submission_link: "https://www.iscb.org/ismb2024/submissions/proceedings"
ismb_abstract_submission_link: "https://www.iscb.org/ismb2024/submissions/abstracts"

#bmc_submission_deadline: ""
#bmc_conditional_accept: ""
#bmc_final_accpet: ""

# Build settings
markdown: kramdown

collections:
    - posters_ISMB

google_analytics: "'UA-22015250-1'"
use_analytics: true
encoding: utf-8
lang: en-US
